### ISSUE TITLE
补充两个网站

### ISSUE THREAD

**Issue by DemerzelSun12** [hitlug/hit-network-resources#1]
* [jwts.hit.edu.cn/kjscx/queryKjs_wdl](http://jwts.hit.edu.cn/kjscx/queryKjs_wdl)（空教室查询系统）：
可查找当前学期所有的空教室情况。

* [jwc.hit.edu.cn](http://jwc.hit.edu.cn/)（教务处网站）：
部分教务信息发布网站，如选课通知、放假安排等。

**Comment by billchenchina** [comment]
感谢你的贡献！已添加
